// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Capability {
    #[prost(string, required, tag = "1")]
    pub endpoint: ::prost::alloc::string::String,
    #[prost(int32, required, tag = "2")]
    pub capacity: i32,
}
