// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeletePortalRequest {
    /// ID of the portal being deleted.
    #[prost(string, tag = "1")]
    pub portal_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeletePortalResponse {
    /// Whether the request was received fine.
    #[prost(bool, tag = "1")]
    pub ok: bool,
    /// Error text.
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdatePortalSizeRequest {
    /// ID of the domain being created.
    #[prost(string, tag = "1")]
    pub portal_id: ::prost::alloc::string::String,
    /// New size of portal.
    #[prost(double, tag = "2")]
    pub size: f64,
    /// The action to do regarding the portal.
    #[prost(enumeration = "UpdatePortalSizeAction", tag = "3")]
    pub action: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdatePortalSizeResponse {
    /// Whether the request was received fine.
    #[prost(bool, tag = "1")]
    pub ok: bool,
    /// Error text.
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum UpdatePortalSizeAction {
    RemovePortalFromDomains = 0,
    DeletePoses = 1,
}
impl UpdatePortalSizeAction {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::RemovePortalFromDomains => "REMOVE_PORTAL_FROM_DOMAINS",
            Self::DeletePoses => "DELETE_POSES",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "REMOVE_PORTAL_FROM_DOMAINS" => Some(Self::RemovePortalFromDomains),
            "DELETE_POSES" => Some(Self::DeletePoses),
            _ => None,
        }
    }
}
