/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct DatastoreWrapper DatastoreWrapper;

typedef struct DomainCluster DomainCluster;

typedef struct DomainData {
  const char *domain_id;
  const char *id;
  const char *name;
  const char *data_type;
  const char *metadata;
  void *content;
  uintptr_t content_size;
} DomainData;

typedef struct DomainError {
  const char *message;
} DomainError;

typedef void (*FindCallback)(void*, const struct DomainData*, const struct DomainError*);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

Query *create_domain_data_query(const char *const *ids_ptr,
                                int len,
                                const char *name,
                                const char *data_type);

void free_domain_data_query(Query *query);

/**
 * Free a DomainData struct
 */
void free_domain_data(struct DomainData *data);

struct DomainCluster *init_domain_cluster(const char *domain_manager_id, Context *peer);

void free_domain_cluster(struct DomainCluster *cluster);

struct DatastoreWrapper *init_remote_storage(struct DomainCluster *cluster, Context *peer);

void free_datastore(struct DatastoreWrapper *store);

void find_domain_data(struct DatastoreWrapper *store,
                      const char *domain_id,
                      Query *query,
                      FindCallback callback,
                      void *user_data);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
