[package]
name = "posemesh-protobuf"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.9.0"
futures = "0.3.31"
prost = "0.13.4"
quick-protobuf = "0.8.1"

[build-dependencies]
prost-build = "0.13.4"
