[package]
name = "auki-p2p"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true
publish = false

[dependencies]
futures = { workspace = true }
jsonwebtoken = "9.3.0"
libp2p = { workspace = true, features = ["tokio", "macros", "noise", "tcp", "yamux"] }
libp2p-stream = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync", "time"] }
uuid = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
