function(ADD_GLM_HEADERS NAME)
    if(NOT TARGET ${NAME})
        message(FATAL_ERROR "Target '${NAME}' does not exist.")
    endif()
    target_include_directories(${NAME} PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../third-party/glm")
endfunction()
