function(GET_BUILD_DIRECTORY_SUFFIX OUT_BUILD_DIRECTORY_SUFFIX)
    if("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
        set(BUILD_TYPE_SUFFIX "Debug")
    else()
        set(BUILD_TYPE_SUFFIX "Release")
    endif()
    if(LINUX)
        if("${CMAKE_SYSTEM_PROCESSOR}" MATCHES "x86_64|amd64")
            set(${OUT_BUILD_DIRECTORY_SUFFIX} "Linux-AMD64-${BUILD_TYPE_SUFFIX}" PARENT_SCOPE)
        elseif("${CMAKE_SYSTEM_PROCESSOR}" MATCHES "arm64|aarch64")
            set(${OUT_BUILD_DIRECTORY_SUFFIX} "Linux-ARM64-${BUILD_TYPE_SUFFIX}" PARENT_SCOPE)
        else()
            message(FATAL_ERROR "Unknown build directory suffix.")
        endif()
    elseif(APPLE)
        if(PLATFORM STREQUAL "MAC")
            set(${OUT_BUILD_DIRECTORY_SUFFIX} "macOS-AMD64-${BUILD_TYPE_SUFFIX}" PARENT_SCOPE)
        elseif(PLATFORM STREQUAL "MAC_ARM64")
            set(${OUT_BUILD_DIRECTORY_SUFFIX} "macOS-ARM64-${BUILD_TYPE_SUFFIX}" PARENT_SCOPE)
        elseif(PLATFORM STREQUAL "MAC_CATALYST")
            set(${OUT_BUILD_DIRECTORY_SUFFIX} "Mac-Catalyst-AMD64-${BUILD_TYPE_SUFFIX}" PARENT_SCOPE)
        elseif(PLATFORM STREQUAL "MAC_CATALYST_ARM64")
            set(${OUT_BUILD_DIRECTORY_SUFFIX} "Mac-Catalyst-ARM64-${BUILD_TYPE_SUFFIX}" PARENT_SCOPE)
        elseif(PLATFORM STREQUAL "OS64")
            set(${OUT_BUILD_DIRECTORY_SUFFIX} "iOS-ARM64-${BUILD_TYPE_SUFFIX}" PARENT_SCOPE)
        elseif(PLATFORM STREQUAL "SIMULATOR64")
            set(${OUT_BUILD_DIRECTORY_SUFFIX} "iOS-Simulator-AMD64-${BUILD_TYPE_SUFFIX}" PARENT_SCOPE)
        elseif(PLATFORM STREQUAL "SIMULATORARM64")
            set(${OUT_BUILD_DIRECTORY_SUFFIX} "iOS-Simulator-ARM64-${BUILD_TYPE_SUFFIX}" PARENT_SCOPE)
        else()
            message(FATAL_ERROR "Unknown build directory suffix.")
        endif()
    elseif(EMSCRIPTEN)
        if(CMAKE_SIZEOF_VOID_P EQUAL 4)
            set(${OUT_BUILD_DIRECTORY_SUFFIX} "Web-WASM32-${BUILD_TYPE_SUFFIX}" PARENT_SCOPE)
        elseif(CMAKE_SIZEOF_VOID_P EQUAL 8)
            set(${OUT_BUILD_DIRECTORY_SUFFIX} "Web-WASM64-${BUILD_TYPE_SUFFIX}" PARENT_SCOPE)
        else()
            message(FATAL_ERROR "Unknown build directory suffix.")
        endif()
    else()
        message(FATAL_ERROR "Unknown build directory suffix.")
    endif()
endfunction()
