name: Posemesh SDK
on: [push]

jobs:
  build_apple_sdk:
    name: Build Apple SDK
    runs-on: macos-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install PowerShell
        run: brew install --cask powershell

      - name: Install Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Build Posemesh Networking (all platforms and architectures)
        run: pwsh ./networking/scripts/Build-Apple.ps1 Release -InstallNecessaryRustToolchainsAndTargets

      - name: Build Posemesh SDK (all platforms and architectures)
        run: pwsh ./sdk/scripts/Build-Apple.ps1 Release

      - name: Bundle Posemesh SDK
        run: |
          pwsh ./sdk/scripts/Bundle-Framework.ps1 macOS Release
          pwsh ./sdk/scripts/Bundle-Framework.ps1 Mac-Catalyst Release
          pwsh ./sdk/scripts/Bundle-Framework.ps1 iOS-Simulator Release
          pwsh ./sdk/scripts/Bundle-XCFramework.ps1 Release
          cd ./sdk/out-Apple-Release
          zip -r -y ./Posemesh.zip ./Posemesh.xcframework

      - name: Get Posemesh SDK version
        run: |
          POSEMESH_SDK_VERSION=$(pwsh ./sdk/scripts/Get-Version.ps1)
          if [[ $? -ne 0 ]]; then echo 'Get-Version.ps1 script failed.' 1>&2; exit 1; fi
          echo "POSEMESH_SDK_VERSION=$POSEMESH_SDK_VERSION" >> $GITHUB_ENV

      - name: Upload Posemesh SDK
        uses: actions/upload-artifact@v4
        with:
          name: Posemesh-Apple-SDK-v${{ env.POSEMESH_SDK_VERSION }}.${{ github.run_number }}
          path: ./sdk/out-Apple-Release/Posemesh.zip
