name: Test Build

on:
  push:
    branches:
      - main
      - feature/*
      - chore/*
      - hotfix/*
      - release/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        architecture: [amd64, arm64, wasm32]
        platform: [linux, browser]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build
        run: |
          echo "Building for ${{ matrix.platform }} on ${{ matrix.architecture }}"
          # If architecture == wasm32, it only needs to build for browser platform
          if [ ${{ matrix.architecture }} == "wasm32" ] && [ ${{ matrix.platform }} != "browser" ]; then
            echo "Skipping build for ${{ matrix.platform }} on ${{ matrix.architecture }}"
            exit 0
          fi
          bash ./networking/scripts/build.sh -p ${{ matrix.platform }} -a ${{ matrix.architecture }} -b Release -i
      
      - name: Build Examples
        if : ${{ github.ref_name == github.event.repository.default_branch }}
        run: |
          echo "Building examples"
          if [ ${{ matrix.architecture }} == "wasm32" ]; then
            echo "Skipping build for ${{ matrix.platform }} on ${{ matrix.architecture }}"
            exit 0
          fi
          bash ./networking/scripts/build.sh -p ${{ matrix.platform }} -a ${{ matrix.architecture }} -b Release -i -e -f rust



      
