/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Networking Networking;

typedef struct Config {
  const char *bootstraps;
  const char *relays;
  const unsigned char *private_key;
  uint32_t private_key_size;
  const char *private_key_path;
  bool enable_mdns;
  const char *name;
} Config;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

struct Networking *psm_posemesh_networking_context_create(const struct Config *config);

void psm_posemesh_networking_context_destroy(struct Networking *context);

uint8_t psm_posemesh_networking_context_send_message(struct Networking *context,
                                                     const void *message,
                                                     uint32_t message_size,
                                                     const char *peer_id,
                                                     const char *protocol,
                                                     void *user_data,
                                                     uint32_t timeout,
                                                     const void *callback);

void psm_posemesh_networking_get_commit_id(char *buffer, unsigned int *size);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
